apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}

